config/routes.rb
Rails.application.routes.draw do
  resources :words
  root 'words#new'

  # get 'home/index'
  get 'wordwall' => 'words#wordwall'
  get 'index' => 'home#index' 
  post '/' => 'words#new' 
  post 'index' => 'home#index'

  get 'home/test'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  	past_searches = []

  	if params[:word].present?
  		parameters = {
      headers: {
        "Accept": "application/json",
        "app_id": "#{ENV['oed_app_id']}",
        "app_key": "#{ENV['oed_app_key']}",
        }
      }
    lemmatron = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/inflections/en/#{params[:word]}", parameters)
    # @grammatical_feature = lemmatron['results'][0]['lexicalEntries'][0]['grammaticalFeatures'][0]['text']
    @inflection = lemmatron['results'][0]['lexicalEntries'][0]['inflectionOf'][0]['text']
	    if @inflection == params[:word]
	    	response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/#{params[:word]}", parameters)
    		@definition = response['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]
    	
    	elsif @inflection != params[:word]
    		response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/#{@inflection}", parameters)
    		@definition = response['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]
    					
 
	    end
    # response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/#{params[:word]}", parameters)
    # @definition = response['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]


 	end
  end

  def test

  	parameters = {
      headers: {
        "Accept": "application/json",
        "app_id": "#{ENV['oed_app_id']}",
        "app_key": "#{ENV['oed_app_key']}",
        }
      }
    response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/ace", parameters)
    @provider = response['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]

    # header = {"Accept": "application/json", 
    # 	"app_id": "#{ENV['oed_app_id']}", 
    # 	"app_key": "#{ENV['oed_app_key']}"}
    # @response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/ace", header)
    # @location = response['name']
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all.order("word ASC")
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
    @words = Word.all.order("created_at DESC")
    if Word.last.present?
      @new_word = Word.last.word
    end
    @definition = "You did it!"

    parameters = {
      headers: {
        "Accept": "application/json",
        "app_id": "#{ENV['oed_app_id']}",
        "app_key": "#{ENV['oed_app_key']}",
        }
      }
    
        if Word.last.present?   
        @response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/#{@new_word}", parameters)
        
          @definition = @response['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]
        end
        
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to root_path, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
        
      parameters = {
      headers: {
        "Accept": "application/json",
        "app_id": "#{ENV['oed_app_id']}",
        "app_key": "#{ENV['oed_app_key']}",
        }
      }
    
        # response = HTTParty.get("https://od-api.oxforddictionaries.com:443/api/v1/entries/en/#{params[:word]}", parameters)
        
        
        # @definition = response['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]

      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def wordwall
    @words = Word.all.order("created_at DESC")
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/home/index.html.erb
<div class="container">
	<h1>WORD WALL</h1>

	<div class="row">

		<div class="col-md-6">
			<div class="card">
			      <h1>Look up a word</h1>
			      <p>Type in a word and get its first definition, courtesy of the Oxford English Dictionary. Sorry, at this time accent marks and other special characters won't work.</p>
			      <div>
			        <%= form_tag index_path do %>
			        <%= text_field_tag :word, nil, placeholder: "type your word", class: "form-control" %><br/>
			        <%= submit_tag "Look it Up", class: "btn btn-primary" %>
			      <% end %>
			    </div>
			 </div>

			  	<div class="card">
				      <!-- Bring in the instance variable from our controller to display on our index page. -->
				      <!-- Check to make sure @location is not empty or nil and that the API did not return an error -->
				      <% if :word != nil %>
				        <h1>Definition for <%= params[:word] %></h1>
				        <div class="row">
				          <div class="col-md-7">
				            <!-- <p><%= @definition%></p> -->
				            <p>Inflection: of <%=@inflection%></p>
				            <p>Definition:<%=@definition%></p>
				          </div>
				        </div>
				        <% elsif @status == "404" %>
				          <p>Error:<%= @error %>. Please Try Again.</p>
				        <% else %>
				          <p>Enter a word to get the definition!</p>
				        <% end %>
				</div>

		</div>

		

	</div>

</div>

app/views/home/test.html.erb
<h1>Oxford English Dictionary JSON response </h1>
<p>Test word: Ace</p>
<!-- <p><%=@response%></p> -->
<p><%=@provider%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordWall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Ranchers" rel="stylesheet">

  </head>

  <body>
    <div id="banner">
      Word WALL
    </div>
    <%= yield %>
    <footer>
      &#169;2018 Kathryn Mueller
    </footer>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Type in a word and get its first definition in the Oxford English Dictionary.</p>

  <div class="field">
    <%= form.text_field :word %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
  <% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= link_to 'Delete', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Word', new_word_path %></p>
<p><%= link_to 'Back to Home', root_path %></p>

app/views/words/new.html.erb
<div class="container">
	<div id="definition">
		<div class="card">
		<%= render 'form', word: @word %>


		  <% if @response != nil %>
		    <h1><%= @new_word %>:</h1>
		    <div class="row">
		      <div class="col-md-7">
		        <p><%=@definition%></p>
		      </div>
		    </div>
		    <% else %>
		      <p>Your definition will appear here.</p>
		    <% end %>
		</div>
	</div>

			<!-- <h2>Your Word Wall</h2>
			<h3>Look up more words to keep building!</h3> -->
			<p>
			<% @words.each do |word| %>
		        <%= word.word %>
		    <% end %>
			</p>
		    <%= link_to 'Edit your Word Wall', words_path %>

</div>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>

app/views/words/wordwall.html.erb
<div>
	<%= render 'form', word: @word %>
</div>

<div>
	<% @words.each do |word| %>
        <p><%= word.word %></p>
    <% end %>
</div>